title: "#10DayWebBuild"
description: "Join the #10DayWebBuild and build a new website over a period of 10 days while posting about it on social media every day."
url: "https://10daywebbuild.netlify.app/"
favicon: "assets/images/favicon.ico"
# logo: ""
image:
  path: "assets/images/preview.png"
  height: 100
  width: 100
twitter:
  username: "SeaFilmz"
  card: "Join the #10DayWebBuild and build a new website over a period of 10 days while posting about it on social media every day."

email: ""
timezone: UTC
baseurl: ""
permalink: "/:title/"
author: ""
paginate: 30
#disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
#ganalytics: UA-113961478-1

# Authors
# authors:
#   sal:
#     name: Sal
#     display_name: Sal
#     avatar: 'assets/images/sal.png'
#     email: wowthemesnet@gmail.com
#     web: https://www.wowthemes.net/category/jekyll-themes/
#     twitter: https://twitter.com/wowthemesnet
#     description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
#   john:
#     name: John
#     display_name: John
#     avatar: 'assets/images/john.png'
#     email: wowthemesnet@gmail.com
#     web: https://www.wowthemes.net/category/jekyll-themes/
#     twitter: https://twitter.com/wowthemesnet
#     description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
# social:
#   instagram: https://www.instagram.com/bootstrapstarter/
#   facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
#   twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
collections:
  community:
    output: true
    permalink: /community/:name
exclude:
  - _community/EXAMPLE.md
  - _community/TEMPLATE.md
